<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MicroservicesArchitecture" nsURI="http://it.univaq.thesis.msa.arch"
    nsPrefix="msa">
  <eAnnotations source="gmf"/>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Element">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedBy" lowerBound="1"
        upperBound="-1" eType="#//MicroService" containment="true" eOpposite="#//MicroService/compose"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dividedIn" upperBound="-1"
        eType="#//Cluster" containment="true" eOpposite="#//Cluster/divide"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" lowerBound="1" upperBound="-1"
        eType="#//Team" containment="true" eOpposite="#//Team/workFor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true" eOpposite="#//Link/Dependency"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developers" upperBound="-1"
        eType="#//Developer" containment="true" eOpposite="#//Developer/worksFor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MicroService" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.style" value="solid"/>
      <details key="label.pattern" value="    {0}"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="border.color" value="0,153,153"/>
      <details key="border.width" value="4"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compose" eType="#//Product"
        eOpposite="#//Product/composedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongTo" eType="#//Cluster"
        eOpposite="#//Cluster/contains"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expose" upperBound="-1"
        eType="#//Interface" containment="true" eOpposite="#//Interface/exposedBy">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owned" eType="#//Team"
        eOpposite="#//Team/workOn">
      <eAnnotations source="gmf.link">
        <details key="target.decoration" value="arrow"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="require" upperBound="-1"
        eType="#//Interface" containment="true" eOpposite="#//Interface/requiredBy">
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//serviceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cluster" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//MicroService" eOpposite="#//MicroService/belongTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="divide" eType="#//Product"
        eOpposite="#//Product/dividedIn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Developer" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="border.width" value="3"/>
      <details key="border.color" value="66,133,244"/>
      <details key="label" value="email"/>
      <details key="border.style" value="dot"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="ellipse"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worksFor" eType="#//Product"
        eOpposite="#//Product/developers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="label" value="endPoint"/>
      <details key="border.style" value="solid"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposedBy" eType="#//MicroService"
        eOpposite="#//MicroService/expose"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" eType="#//MicroService"
        eOpposite="#//MicroService/require"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Element">
    <eAnnotations source="gmf.link">
      <details key="color" value="0,26,26"/>
      <details key="label.icon" value="false"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="source.decoration" value="filledrhomb"/>
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Dependency" eType="#//Product"
        eOpposite="#//Product/links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="border.width" value="3"/>
      <details key="border.color" value="66,133,244"/>
      <details key="label" value="name"/>
      <details key="label.placement" value="internal"/>
      <details key="border.style" value="solid"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="ellipse"/>
      <details key="size" value="150,70"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedBy" upperBound="-1"
        eType="#//Developer">
      <eAnnotations source="gmf.link">
        <details key="color" value="66,133,244"/>
        <details key="target.decoration" value="none"/>
        <details key="style" value="dash"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workOn" upperBound="-1"
        eType="#//MicroService" eOpposite="#//MicroService/owned"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workFor" eType="#//Product"
        eOpposite="#//Product/teams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="serviceType">
    <eLiterals name="generalFuncion"/>
    <eLiterals name="Authentication" value="1"/>
    <eLiterals name="serviceDiscovery" value="2"/>
    <eLiterals name="LoadBalancer" value="3"/>
    <eLiterals name="HealthCheck" value="4"/>
    <eLiterals name="Monitor" value="5"/>
    <eLiterals name="APIGateways" value="6"/>
    <eLiterals name="Security" value="7"/>
    <eLiterals name="Messaging" value="8"/>
    <eLiterals name="Logging" value="9"/>
    <eLiterals name="Resilience" value="10"/>
  </eClassifiers>
</ecore:EPackage>
