<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="MicroservicesArchitecture" nsURI="http://it.univaq.thesis.msa.arch"
    nsPrefix="msa">
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Element">
    <eAnnotations source="gmf.diagram"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedBy" lowerBound="1"
        upperBound="-1" eType="#//MicroService" containment="true" eOpposite="#//MicroService/compose">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dividedIn" upperBound="-1"
        eType="#//Cluster" containment="true" eOpposite="#//Cluster/divide">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="teams" lowerBound="1" upperBound="-1"
        eType="#//Team" containment="true" eOpposite="#//Team/workFor">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="links" upperBound="-1"
        eType="#//Link" containment="true" eOpposite="#//Link/dependency">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="developers" upperBound="-1"
        eType="#//Developer" containment="true" eOpposite="#//Developer/worksFor">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MicroService" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.style" value="solid"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
      <details key="color" value="178,255,102"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Product"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compose" eType="#//Product"
        eOpposite="#//Product/composedBy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belongTo" eType="#//Cluster"
        eOpposite="#//Cluster/contains">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expose" upperBound="-1"
        eType="#//Interface" containment="true" eOpposite="#//Interface/exposedBy">
      <eAnnotations source="gmf.affixed"/>
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="host" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="owned" eType="#//Team"
        eOpposite="#//Team/workOn">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="require" upperBound="-1"
        eType="#//Interface" containment="true" eOpposite="#//Interface/requiredBy">
      <eAnnotations source="gmf.affixed"/>
      <eAnnotations source="gmf.compartment">
        <details key="collapsible" value="true"/>
        <details key="layout" value="list"/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//serviceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Cluster" eSuperTypes="#//Element">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Product"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" upperBound="-1"
        eType="#//MicroService" eOpposite="#//MicroService/belongTo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="divide" eType="#//Product"
        eOpposite="#//Product/dividedIn"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Developer" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="label" value="name"/>
      <details key="border.style" value="dot"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rounded"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Product"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="email" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="username" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="worksFor" eType="#//Product"
        eOpposite="#//Product/developers"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="#//Element">
    <eAnnotations source="gmf.node">
      <details key="color" value="104,199,246"/>
      <details key="label" value="endPoint"/>
      <details key="border.style" value="dash"/>
      <details key="label.icon" value="false"/>
      <details key="figure" value="rectangle"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Product"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exposedBy" eType="#//MicroService"
        eOpposite="#//MicroService/expose"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endPoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredBy" eType="#//MicroService"
        eOpposite="#//MicroService/require"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Link" eSuperTypes="#//Element">
    <eAnnotations source="gmf.link">
      <details key="color" value="255,0,0"/>
      <details key="label" value="name"/>
      <details key="label.icon" value="false"/>
      <details key="source" value="source"/>
      <details key="target" value="target"/>
      <details key="source.decoration" value="filledrhomb"/>
      <details key="target.decoration" value="arrow"/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Product"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//Interface">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Interface">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependency" eType="#//Product"
        eOpposite="#//Product/links"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Team" eSuperTypes="#//Element">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Product"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composedBy" upperBound="-1"
        eType="#//Developer">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="Product"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workOn" upperBound="-1"
        eType="#//MicroService" eOpposite="#//MicroService/owned"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workFor" eType="#//Product"
        eOpposite="#//Product/teams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="serviceType">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="Product"/>
    </eAnnotations>
    <eLiterals name="functional" literal="functional"/>
    <eLiterals name="monitoring" value="1"/>
    <eLiterals name="system_level_management" value="3"/>
    <eLiterals name="service_orchestration" value="4"/>
    <eLiterals name="service_brokering" value="5"/>
    <eLiterals name="security" value="6"/>
    <eLiterals name="service_proxy" value="7"/>
    <eLiterals name="data_storage" value="8"/>
  </eClassifiers>
</ecore:EPackage>
